<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mdown</string>
		<string>markdown</string>
		<string>markdn</string>
		<string>md</string>
	</array>
	<key>name</key>
	<string>Markdown Light</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#raw_indented_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>^(?=\s*+\S)</string>
			<key>end</key>
			<string>^(?=\s*+$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fenced_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#horizontal_rule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list_item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#maybe_setext_heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>bold</key>
		<dict>
			<key>begin</key>
			<string>(?x)
(?&lt;=^|_|\W)
(\*\*|__)
(?=\S*?[^\W_](?:.*?[^\W_])?\S*?\1[_\*]*($|\W))
</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)\1(?=[_\*]*($|\W))</string>
			<key>name</key>
			<string>markup.bold.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>bold_italic</key>
		<dict>
			<key>begin</key>
			<string>(?x)
(?&lt;=^|_|\W)
(\*\*\*|___)
(?=\S*?[^\W_](?:.*?[^\W_])?\S*?\1[_\*]*($|\W))
</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bold.markdown punctuation.definition.italic.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)\1(?=[_\*]*($|\W))</string>
			<key>name</key>
			<string>markup.bold.markdown markup.italic.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>email</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?xi)
(?:
  (&lt;)
  (
    (?:mailto:)?
    [-a-z\d_%~\.]++@
    (?:(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)
    (?:\.(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)*
    (?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,}))
  )
  (&gt;)
  |
  (
    (?:mailto:)?
    [-a-z\d_%~\.]++@
    (?:(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)
    (?:\.(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)*
    (?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,}))
  )
)
</string>
			<key>name</key>
			<string>meta.link.email.markdown</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\[-`*_#+.!(){}\[\]\\&gt;]</string>
			<key>name</key>
			<string>constant.character.escape.markdown</string>
		</dict>
		<key>fenced_block</key>
		<dict>
			<key>begin</key>
			<string>^(?=\s*```\s*[^\s`]*\s*$)</string>
			<key>end</key>
			<string>^(?=\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fenced_blocks</string>
				</dict>
			</array>
		</dict>
		<key>fenced_blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(html|html5)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(xml)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.xml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(diff)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.diff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(perl)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.perl</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(php)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.php</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(css)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(less)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.css.less</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(java)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.java</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(c)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(c\+\+)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c++</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(yaml)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.yaml</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(sql)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(shell)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(sass|scss)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sass</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(scala)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.scala</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(objective-c)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.objc</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(coffee)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.coffee</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(js|json|javascript)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(ruby)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(python)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.python</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(go|golang)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.go</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(rs|rust)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.rust</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*(swift)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.swift</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\s*```)\s*([^\s`]*)\s*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.fenced.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.language.fenced.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\1)\n</string>
					<key>name</key>
					<string>markup.raw.block.markdown markup.raw.block.fenced.markdown</string>
				</dict>
			</array>
		</dict>
		<key>heading</key>
		<dict>
			<key>begin</key>
			<string>^(#{1,6})(?!#)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.heading.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>entity.name.section.markdown</string>
			<key>end</key>
			<string>\s*(#*)$</string>
			<key>name</key>
			<string>markup.heading.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>horizontal_rule</key>
		<dict>
			<key>match</key>
			<string>^\s*+([-_*])\s*+(?:\1\s*){2,}+$</string>
			<key>name</key>
			<string>meta.separator.markdown</string>
		</dict>
		<key>html_block</key>
		<dict>
			<key>begin</key>
			<string>(?x)
^(?=&lt;(
  p|div|h[1-6]|blockquote|pre|table|dl|
  ol|ul|script|noscript|form|fieldset|iframe|math|ins|del
)\b[^&gt;]*&gt;)
</string>
			<key>end</key>
			<string>(?&lt;=&lt;/\1&gt;)</string>
			<key>name</key>
			<string>meta.disable-markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>image</key>
		<dict>
			<key>begin</key>
			<string>(!)(\[)(?=[^\]]*\]\s*\([^\)]*\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.image.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.link.title.markdown</string>
			<key>end</key>
			<string>(\])\s*(\()\s*([^\)]*?)(?:\s+(")(.*)("))?\s*(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.image.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.image.inline.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>implicit_image</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.image.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(!)(\[)([^\]]+)(\])\s*(\[)\s*(\])</string>
			<key>name</key>
			<string>meta.image.reference.markdown</string>
		</dict>
		<key>implicit_link</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)([^\]]+)(\])\s*(\[)\s*(\])</string>
			<key>name</key>
			<string>meta.link.reference.literal.markdown</string>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline_raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#implicit_image</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference_image</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#implicit_link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reference_link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#url</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold_italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strikethrough</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#manual_line_break</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valid_ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valid_bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>inline_raw</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.raw.inline.content.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.raw.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(`+)(.+?)(\1)</string>
			<key>name</key>
			<string>markup.raw.inline.markdown</string>
		</dict>
		<key>italic</key>
		<dict>
			<key>begin</key>
			<string>(?x)
(?&lt;=^|_|\W)
(\*|_)
(?=\S*?[^\W_](?:.*?[^\W_])?\S*?\1[_\*]*($|\W))
</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.italic.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)\1(?=[_\*]*($|\W))</string>
			<key>name</key>
			<string>markup.italic.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>link</key>
		<dict>
			<key>begin</key>
			<string>\[(?=[^\]]*\]\s*\([^\)]*\))</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.link.title.markdown</string>
			<key>end</key>
			<string>(\])\s*(\()\s*([^\)]*?)(?:\s+(")(.*)("))?\s*(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.metadata.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.link.inline.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>list_item</key>
		<dict>
			<key>begin</key>
			<string>^(?=\s*([*+-]|\d+\.)[ ])</string>
			<key>end</key>
			<string>^(?=\s*([*+-]|\d+\.)[ ]|\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numbered_list_item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#unnumbered_list_item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#list_item_continuation</string>
				</dict>
			</array>
		</dict>
		<key>list_item_continuation</key>
		<dict>
			<key>begin</key>
			<string>^(?=\s+\S)</string>
			<key>end</key>
			<string>^(?=\s*(?:[*+-]|\d+\.)[ ]|\s*```\s*[^\s`]*\s*$|\s*$)</string>
			<key>name</key>
			<string>meta.paragraph.list.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>manual_line_break</key>
		<dict>
			<key>match</key>
			<string>  +$</string>
			<key>name</key>
			<string>meta.dummy.line-break</string>
		</dict>
		<key>maybe_setext_heading</key>
		<dict>
			<key>begin</key>
			<string>^(?!\s*$|(?:={3,}|-{3,}))</string>
			<key>end</key>
			<string>^(?!(?:={3,}|-{3,})\s*$)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#setext_heading_1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#setext_heading_2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>numbered_list_item</key>
		<dict>
			<key>begin</key>
			<string>^\s*(\d+\.)[ ]</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.markdown punctuation.definition.list_item.number.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\s*(?:[*+-]|\d+\.)[ ]|\s*```\s*[^\s`]*\s*$|\s*$)</string>
			<key>name</key>
			<string>meta.paragraph.list.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>quoted_block</key>
		<dict>
			<key>begin</key>
			<string>^[ ]{,3}(&gt;)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.blockquote.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\s*$|[ ]{,3}&gt;)</string>
			<key>name</key>
			<string>markup.quote.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>raw_indented_block</key>
		<dict>
			<key>match</key>
			<string>^(?:[ ]{4}|\t)\s*+\S.*+$\n?</string>
			<key>name</key>
			<string>markup.raw.block.markdown</string>
		</dict>
		<key>reference</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.link.reference.def.markdown</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>string.other.link.description.title.markdown</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.markdown</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((\[)([^\]]*)(\])(:)\s*(?:(&lt;)([^&gt;]+)(&gt;)|([^&lt;&gt;\s]+))(?:\s+(?:(['"])(.*)(\10)|(\()(.*)(\))))?)\s*$</string>
		</dict>
		<key>reference_image</key>
		<dict>
			<key>begin</key>
			<string>(!)(\[)(?=[^\]]*\]\s*\[[^\]]+\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.image.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.link.title.markdown</string>
			<key>end</key>
			<string>(\])\s*(\[)\s*([^\]]+)\s*(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.image.reference.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>reference_link</key>
		<dict>
			<key>begin</key>
			<string>\[(?=[^\]]*\]\s*\[[^\]]+\])</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.markdown</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.other.link.title.markdown</string>
			<key>end</key>
			<string>(\])\s*(\[)\s*([^\]]+)\s*(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.link.reference.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>setext_heading_1</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.1.markdown punctuation.definition.heading.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(={3,})\s*$</string>
		</dict>
		<key>setext_heading_2</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.heading.2.markdown punctuation.definition.heading.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(-{3,})\s*$</string>
		</dict>
		<key>strikethrough</key>
		<dict>
			<key>begin</key>
			<string>(?x)
(?&lt;=^|_|\W)
(~~)
(?=\S*?[^\W_](?:.*?[^\W_])?\S*?\1[_\*]*($|\W))
</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.strikethrough.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=\S)\1(?=[_\*]*($|\W))</string>
			<key>name</key>
			<string>markup.strikethrough.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>unnumbered_list_item</key>
		<dict>
			<key>begin</key>
			<string>^\s*([*+-])[ ]</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.list_item.markdown</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=\s*(?:[*+-]|\d+\.)[ ]|\s*```\s*[^\s`]*\s*$|\s*$)</string>
			<key>name</key>
			<string>meta.paragraph.list.markdown</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline</string>
				</dict>
			</array>
		</dict>
		<key>url</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.link.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?xi)
(?:
  (&lt;)
  (
    (?:(?:https?|ftp)://)
    (?:\S+(?::\S*)?@)?
    (?:
    (?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])
    (?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}
    (?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))
    |
    (?:(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)
    (?:\.(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)*
    (?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,}))
    \.?
    )
    (?::\d{2,5})?
    (?:[/?#](?:\S*[^_*\s]+)?)?
  )
  (&gt;)
)
|
(
  (?:(?:https?|ftp)://)
  (?:\S+(?::\S*)?@)?
  (?:
  (?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])
  (?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}
  (?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))
  |
  (?:(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)
  (?:\.(?:[\da-z\x{00a1}-\x{ffff}][-_]*)*[\da-z\x{00a1}-\x{ffff}]+)*
  (?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,}))
  \.?
  )
  (?::\d{2,5})?
  (?:[/?#](?:\S*[^_*\s]+)?)?
)
</string>
			<key>name</key>
			<string>meta.link.inet.markdown</string>
		</dict>
		<key>valid_ampersand</key>
		<dict>
			<key>match</key>
			<string>&amp;(?!([a-zA-Z\d]+|#\d+|#x[\da-fA-F]+);)</string>
			<key>name</key>
			<string>meta.other.valid-ampersand.markdown</string>
		</dict>
		<key>valid_bracket</key>
		<dict>
			<key>match</key>
			<string>(?i)&lt;(?![a-z\d?%:!]|/[a-z\d])</string>
			<key>name</key>
			<string>meta.other.valid-bracket.markdown</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown</string>
	<key>uuid</key>
	<string>0A1D9875-B448-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
